### ISSUE TITLE
Why is there djongo in the engine in settings?

### ISSUE THREAD

**Issue by the-lost-kite** [mongodb-developer/django-pymongo#1]

**Comment by ykutaykuta** [comment]
I also have the same question, and I think the reason is avoid the following issue:
`Internal Server Error: /
Traceback (most recent call last):
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/contrib/sessions/middleware.py", line 59, in process_response
    request.session.save()
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 80, in save
    return self.create()
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 50, in create
    self._session_key = self._get_new_session_key()
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 150, in _get_new_session_key
    if not self.exists(session_key):
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 46, in exists
    return self.model.objects.filter(session_key=session_key).exists()
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1226, in exists
    return self.query.has_results(using=self.db)
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 592, in has_results
    return compiler.has_results()
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1366, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1385, in execute_sql
    sql, params = self.as_sql()
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 615, in as_sql
    from_, f_params = self.get_from_clause()
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 977, in get_from_clause
    clause_sql, clause_params = self.compile(from_clause)
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 506, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/datastructures.py", line 199, in as_sql
    base_sql = compiler.quote_name_unless_alias(self.table_name)
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 497, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/home/ykuta/projects/venv/lib/python3.10/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.`
